# packages- issues or vulnerabilities (scan)
#pip-audit

name: Dependency Scan

on:
    workflow_call

jobs:
    dependency-check:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python 3.12
              uses: actions/setup-python@v5
              with: 
                python-version: 3.12

            - name: Install Pip Audit #Package that helps in auditing
              run: pip install pip-audit

            - name: Audit Dependencies
              run: pip-audit -r requirements.txt