# This will deploy the safe tested app to Prod Server

name: Deploy to Server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

            - name: Debug Key Length
              run: echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | wc -c
              
            - name: SSh to Prod Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                    echo "Staring deployment"
                    mkdir -p devops
                

