name: Deploy Flask App

on:
    workflow_dispatch:

jobs:
    deploy:
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        runs-on: self-hosted

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup docker compose
          uses: docker/setup-compose-action@v2

        - name: Debug repo structure
          run: |
            echo "Current path:"
            pwd
            echo "Files:"
            ls -R

        - name: Deploy with Docker Compose
          run: docker compose -f docker-compose.yml up -d --build