# Uses Trivy Image scanning for CVEs
name: Docker Image Scanner

on:
    workflow_call

jobs:
    image-scanner:
        runs-on: ubuntu-latest

        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Trivy Scanner
              uses: aquasecurity/trivy-action@v0.65.0
              with:
                image-ref: ${{ vars.DOCKERHUB_USER }}/flask-app:latest
                severity: 'CRITICAL'
                exit-code: '1'
              

